# Generated by Django 6.0.1 on 2026-01-18 19:38

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='creators')
    Group.objects.get_or_create(name='subscribers')

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_ticket_review_userfollows'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
